// portfolio-vue/src/components/ApproachSection.vue
<template>
  <div ref="el">
    <span class="panel__dock-intro fade-in">How I work</span>
    <p class="approach__lede fade-in" style="transitionDelay: 0.08s">
      Clean design, careful engineering. Every detail is chosen on purpose —
      whether in code, composition, or color.
    </p>
    <div class="approach__steps">
      <div v-for="(s, i) in steps" :key="s.num" class="approach__step fade-in" :style="{ transitionDelay: 0.16 + i * 0.1 + 's' }">
        <span class="approach__num">{{ s.num }}</span>
        <h3 class="approach__name">{{ s.name }}</h3>
        <p class="approach__copy">{{ s.copy }}</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const el = ref(null)

onMounted(() => {
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.querySelectorAll('.fade-in').forEach((el, i) => {
          setTimeout(() => el.classList.add('visible'), i * 80)
        })
        observer.unobserve(entry.target)
      }
    })
  }, { threshold: 0.2 })
  if (el.value) observer.observe(el.value)
})

const steps = [
  {
    num: '01', name: 'Listen',
    copy: 'Every project starts with understanding — the goal, the audience, the story. Whether it is code, a photograph, or a brand identity, I listen first.'
  },
  {
    num: '02', name: 'Create',
    copy: 'Ideas take shape through sketching, prototyping, and experimentation. Low-fidelity first, then refined until every element has a purpose.'
  },
  {
    num: '03', name: 'Deliver',
    copy: 'Craft meets execution. Clean code, composed frames, and cohesive visuals — delivered with care and attention to every detail.'
  }
]
</script>

// portfolio-react/src/components/ApproachSection.jsx
import { motion } from 'framer-motion'

const steps = [
  {
    num: '01', name: 'Listen',
    copy: 'Every project starts with understanding — the goal, the audience, the story. Whether it is code, a photograph, or a brand identity, I listen first.'
  },
  {
    num: '02', name: 'Create',
    copy: 'Ideas take shape through sketching, prototyping, and experimentation. Low-fidelity first, then refined until every element has a purpose.'
  },
  {
    num: '03', name: 'Deliver',
    copy: 'Craft meets execution. Clean code, composed frames, and cohesive visuals — delivered with care and attention to every detail.'
  }
]

const container = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.15 } }
}

const item = {
  hidden: { opacity: 0, y: 30 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: [0.16, 1, 0.3, 1] } }
}

function ApproachSection() {
  return (
    <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6 }}>
      <span className="panel__dock-intro">How I work</span>
      <motion.p
        className="approach__lede"
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.8, delay: 0.15 }}
      >
        Clean design, careful engineering. Every detail is chosen on purpose —
        whether in code, composition, or color.
      </motion.p>

      <motion.div variants={container} initial="hidden" whileInView="show" viewport={{ once: true }} className="approach__steps">
        {steps.map((s) => (
          <motion.div key={s.num} variants={item} className="approach__step">
            <span className="approach__num">{s.num}</span>
            <h3 className="approach__name">{s.name}</h3>
            <p className="approach__copy">{s.copy}</p>
          </motion.div>
        ))}
      </motion.div>
    </motion.div>
  )
}

export default ApproachSection
